/**
 * Cleans text generated by VLM models by removing unwanted tokens and normalizing whitespace.
 *
 * @param {string} text - The raw text from the VLM model
 * @returns {string} Cleaned text without special tokens and normalized whitespace
 */
export function cleanText(text: string): string {
  return text
    .replace(/<end_of_utterance>/g, "")
    .replace(/<\|im_start\|>/g, "")
    .replace(/<\|im_end\|>/g, "")
    .replace(/<start>/g, "")
    .replace(/<stop>/g, "")
    .replace(/<\/s>/g, "")
    .replace(/<eos>/g, "")
    .replace(/<\/?[^>]+(>|$)/g, "")
    .replace(/\s+/g, " ") 
    .trim();
}

/**
 * Removes extra whitespace and normalizes line breaks.
 *
 * @param {string} text - The text to normalize
 * @returns {string} Normalized text
 */
export function normalizeText(text: string): string {
  return text
    .replace(/\r\n/g, "\n") // Convert Windows line endings
    .replace(/\r/g, "\n") // Convert Mac line endings
    .replace(/\n{3,}/g, "\n\n") // Limit consecutive line breaks to 2
    .replace(/[ \t]+/g, " ") // Normalize spaces and tabs
    .trim();
}
